# Generated by Django 3.1.3 on 2020-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_logs',
            name='actioned_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Actioned On'),
        ),
    ]
