# Generated by Django 3.1.3 on 2021-01-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210110_1817'),
        ('files_logs', '0002_auto_20201203_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=1000, verbose_name='Action Type')),
                ('actioned_on', models.DateTimeField(auto_now_add=True, verbose_name='Actioned On')),
                ('account_id', models.CharField(blank=True, max_length=1000, verbose_name='Account ID')),
                ('status', models.CharField(blank=True, max_length=1000, verbose_name='Action Status')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=1000, verbose_name='File Name')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files_logs.action')),
            ],
        ),
        migrations.CreateModel(
            name='FileJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='files_logs.file')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='jobs.job')),
            ],
        ),
        migrations.DeleteModel(
            name='files_logs',
        ),
    ]
