# Generated by Django 3.1.3 on 2021-01-04 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20210105_0218'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='quantity_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_10',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_4',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_5',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_6',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_7',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_8',
        ),
        migrations.RemoveField(
            model_name='job',
            name='quantity_9',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_10',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_3',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_4',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_5',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_6',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_7',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_8',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_no_9',
        ),
        migrations.CreateModel(
            name='JobService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.service')),
            ],
        ),
    ]
