# Generated by Django 3.1.3 on 2021-01-04 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20210105_0218'),
        ('jobs', '0002_auto_20210105_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobservice',
            name='service_code',
        ),
        migrations.AddField(
            model_name='jobservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reporting.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobservice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.job'),
        ),
    ]
