# Generated by Django 3.1.3 on 2021-01-08 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210105_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='notification_no',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Notification Number'),
        ),
        migrations.AlterField(
            model_name='jobservice',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='jobs.job'),
        ),
    ]
