# Generated by Django 3.1.3 on 2021-01-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20210111_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('New', 'New'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Archived', 'Archived'), ('Off Hold', 'Off Hold')], default='In Progress', max_length=11, verbose_name='Job Status'),
        ),
    ]
