job_headers = [
    'Notification Number',
    'Notification type',
    'Job Type',
    'Work center',
    'Functional Location',
    'Work order Number',
    'Operation',
    'Operation descrition',
    'Notification Long Text(Comments 150 chars)',
    'Task Number',
    'Task Code',
    'Task Long Text',
    'Task completion date',
    'Task completed by',
    'Task User Status (SHLD)',
    'Task User Status (VARQ)',
    'Task User Status (REIC)',
    'Task User Status (TRMG)',
    'Task User Status (CPLS)',
    'Code Group1',
    'Activity Code1',
    'Activity Start Date1',
    'Activity End date1',
    'Activity long Text1',
    'Quantity Factor1',
    'Meter Number',
    'Meter Model',
    'Install Date',
    'Meter Type',
    'Meter Reading',
    'Pressure',
    'Meter Possition',
    'Service Alignment',
    'Removed Meter Number',
    'Removed Model',
    'Removed Date',
    'Removed Meter Reading',
    'New Regulator Serial No',
    'Old Regulator Serial Number',
    'Service No 1.',
    'Quantity 1',
    'Service No 2.',
    'Quantity 2',
    'Service No 3.',
    'Quantity 3',
    'Service No 4.',
    'Quantity 4',
    'Service No 5.',
    'Quantity 5',
    'Service No 6.',
    'Quantity 6',
    'Service No 7.',
    'Quantity 7',
    'Service No 8.',
    'Quantity 8',
    'Service No 9.',
    'Quantity 9',
    'Service No 10.',
    'Quantity 10',
]
