# Generated by Django 3.1.3 on 2020-12-01 04:05

from django.db import migrations, models
import ftpserver.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FTPTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=ftpserver.ftp.FTPStorage(), upload_to='ftp_files')),
            ],
        ),
    ]
