# Generated by Django 3.1.3 on 2021-01-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1000, null=True, verbose_name='New Service Code')),
                ('sap_code', models.CharField(blank=True, max_length=1000, null=True, verbose_name='SAP Code')),
                ('drawing', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Drawing')),
                ('service_type', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Service Type')),
                ('service_description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Service Description')),
                ('rate_type', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Rate Type')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes')),
                ('wa_utilities_rate', models.CharField(blank=True, max_length=1000, null=True, verbose_name='WA Utilities Rate')),
                ('subby_rate', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Subby Rate')),
            ],
        ),
    ]
